"""add fundamental records

Revision ID: 347812d99574
Revises: 8df8fbb0ba67
Create Date: 2026-10-04 23:37:56.709933

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '347812d99574'
down_revision: str | Sequence[str] | None = '8df8fbb0ba67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_records',
    sa.Column('fundamental_record_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('fundamental_record_id'),
    sa.UniqueConstraint('instrument_id', 'period_end', 'metric_name', 'fiscal_year', 'fiscal_quarter', name='uq_fundamental_record_period_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundamental_records')
    # ### end Alembic commands ###
