"""add market bars

Revision ID: 8df8fbb0ba67
Revises: a4a086de3451
Create Date: 2026-10-01 23:14:36.498577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df8fbb0ba67'
down_revision: Union[str, Sequence[str], None] = 'a4a086de3451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('exchanges',
    sa.Column('exchange_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('exchange_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_primary_listing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('market_holidays',
    sa.Column('holiday_id', sa.Uuid(), nullable=False),
    sa.Column('exchange_id', sa.Uuid(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('exchange_id', 'holiday_date', name='uq_market_holiday_exchange_date')
    )
    op.create_table('instrument_history',
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.exchange_id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('market_bars',
    sa.Column('market_bar_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('market_bar_id'),
    sa.UniqueConstraint('instrument_id', 'timestamp', name='uq_market_bar_instrument_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_bars')
    op.drop_table('instrument_history')
    op.drop_table('market_holidays')
    op.drop_table('instruments')
    op.drop_table('exchanges')
    op.drop_table('companies')
    # ### end Alembic commands ###
